/**
 * SportyBet market ID catalogue.
 * Market IDs and descriptions were confirmed against live SportyBet responses
 * (see README "API source"). Used to pick which market IDs to request from the
 * fixtures endpoint and to resolve display names when needed.
 */
export const MARKET_CATALOGUE: ReadonlyArray<readonly [string, string]> = [
  ["1", "1X2"],
  ["60100", "1X2 - 2UP"],
  ["60200", "1X2 - 1UP"],
  ["60210", "1X2 - Never Down"],
  ["60110", "Double Chance - 1UP"],
  ["10", "Double Chance"],
  ["11", "Draw No Bet"],
  ["12", "Home No Bet"],
  ["13", "Away No Bet"],
  ["14", "Handicap"],
  ["15", "Winning Margin"],
  ["16", "Asian Handicap -1.5"],
  ["18", "Over/Under"],
  ["19", "South Africa Over/Under"],
  ["20", "Ivory Coast Over/Under"],
  ["21", "Exact Goals"],
  ["23", "Home Team Goals"],
  ["24", "Away Team Goals"],
  ["25", "Goal Range"],
  ["26", "Odd/Even"],
  ["27", "Home Team Odd/Even"],
  ["28", "Away Team Odd/Even"],
  ["29", "GG/NG"],
  ["30", "Teams to Score"],
  ["31", "Home Team Clean Sheet"],
  ["32", "Away Team Clean Sheet"],
  ["33", "Home Team to Win to Nil"],
  ["34", "Away Team to Win to Nil"],
  ["35", "1X2 & GG/NG"],
  ["36", "Over/Under & GG/NG"],
  ["37", "1X2 & Over/Under 1.5"],
  ["41", "Correct Score [0:0]"],
  ["45", "Correct Score"],
  ["46", "Half Time/Full Time Correct Score"],
  ["47", "Half Time/Full Time"],
  ["48", "Home Team to Win Both Halves"],
  ["49", "Away Team to Win Both Halves"],
  ["50", "Home Team to Win Either Half"],
  ["51", "Away Team to Win Either Half"],
  ["52", "Highest Scoring Half"],
  ["55", "1st/2nd Half GG/NG"],
  ["56", "Home Team to Score In Both Halves"],
  ["57", "Away Team to Score In Both Halves"],
  ["58", "Both Halves Over 1.5"],
  ["59", "Both Halves Under 1.5"],
  ["60", "1st Half - 1X2"],
  ["63", "1st Half - Double Chance"],
  ["64", "1st Half - Draw No Bet"],
  ["65", "1st Half - Handicap"],
  ["68", "1st Half - Over/Under"],
  ["71", "1st Half - Exact Goals"],
  ["74", "1st Half - Odd/Even"],
  ["75", "1st Half - GG/NG"],
  ["76", "1st Half - Home Team Clean Sheet"],
  ["77", "1st Half - Away Team Clean Sheet"],
  ["78", "1st Half - 1X2 & GG/NG"],
  ["81", "1st Half - Correct Score"],
  ["83", "2nd Half - 1X2"],
  ["85", "2nd Half - Double Chance"],
  ["86", "2nd Half - Draw No Bet"],
  ["87", "2nd Half - Handicap"],
  ["90", "2nd Half - Over/Under"],
  ["93", "2nd Half - Exact Goals"],
  ["95", "2nd Half - GG/NG"],
  ["98", "2nd Half - Correct Score"],
  ["162", "Corners - 1X2"],
  ["163", "1st Corner"],
  ["164", "Last Corner"],
  ["165", "Corner Handicap"],
  ["166", "Corners - Over/Under"],
  ["172", "Odd/Even Corners"],
  ["184", "1st Goal & 1X2"],
];

export function marketNameForId(id: string): string | undefined {
  return MARKET_CATALOGUE.find(([marketId]) => marketId === id)?.[1];
}

/** Default market set requested from the fixtures endpoint (kept modest to avoid overload). */
export const DEFAULT_MARKET_IDS = ["1", "18", "10", "29", "11", "26", "36", "14", "60100"];